# Generated by Django 5.0.1 on 2024-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cartitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_item', models.ManyToManyField(to='mainapp.item')),
            ],
        ),
    ]
