# Generated by Django 5.0.1 on 2024-03-11 15:05

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_hotdealsproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', prose.fields.DocumentContentField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.itemcontent'),
        ),
    ]
