# Generated by Django 5.0.1 on 2024-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_order_customer_name_order_shipping_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(to='mainapp.item'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
