# Generated by Django 5.0.1 on 2024-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_itemorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='ordered_items',
            field=models.ManyToManyField(to='mainapp.item'),
        ),
    ]
