# Generated by Django 5.0.1 on 2024-03-11 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_itemorder_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='name',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='is_ordered_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorder',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='shipping_area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
