# Generated by Django 5.0.1 on 2024-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_itemorder_phone_number_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='ordered_items',
            field=models.ManyToManyField(to='mainapp.item'),
        ),
    ]
